import { useEffect, useState, type CSSProperties, type ReactElement, type ReactNode } from "react";
import type { Bridge } from "@particle-editor/bridge-schema";
import { cn } from "@/lib/utils";
import { useRecordHeadless } from "@/lib/record-mode";
import { APP_NAME, UNTITLED_DOC } from "@/lib/window-title";
// The in-app corner mark: the ramped tile icon, byte-for-byte the taskbar/exe
// artwork (generated by src/Resources/icon-src/build.py from logo.ico's 40px
// frame). `?inline` embeds it as a data URI so it resolves under WebView2's
// custom app scheme without an asset path.
import appMark from "@/assets/app-mark.png?inline";

// WebView2 non-client region support: `app-region: drag` makes a region the
// window's draggable caption; `no-drag` opts back out (buttons, menus). Cast
// through `unknown` because it's not in React's CSSProperties.
const DRAG = { WebkitAppRegion: "drag" } as unknown as CSSProperties;
const NO_DRAG = { WebkitAppRegion: "no-drag" } as unknown as CSSProperties;

// Same basename split window-title.ts uses.
function basename(path: string): string {
  const idx = Math.max(path.lastIndexOf("/"), path.lastIndexOf("\\"));
  return idx >= 0 ? path.slice(idx + 1) : path;
}

function WinButton({
  label,
  close,
  onClick,
  children,
}: {
  label: string;
  close?: boolean;
  onClick: () => void;
  children: ReactNode;
}): ReactElement {
  return (
    <button
      type="button"
      aria-label={label}
      title={label}
      // Native window controls aren't in the app's tab order (keyboard users
      // reach them via Alt+Space → the system menu, which the HTCAPTION hit-test
      // provides). Keeps the app's tab cycle unchanged.
      tabIndex={-1}
      onClick={onClick}
      className={cn(
        "flex w-[46px] items-center justify-center text-text-2 transition-colors",
        // Theme-aware hover/pressed via the border tokens — clearly visible AND
        // correct-direction in both modes (lightens on the dark panel, darkens on
        // the light one; press goes one step further). Close keeps the universal
        // red with a darker pressed red.
        close
          ? "hover:bg-[#e81123] hover:text-white active:bg-[#c50f1f] active:text-white"
          : "hover:bg-border hover:text-text active:bg-border-2 active:text-text",
      )}
    >
      {children}
    </button>
  );
}

export interface TitleBarProps {
  bridge: Bridge;
  currentFilePath: string | null;
  dirty: boolean;
}

/**
 * The app's frameless custom title bar. Left: the real app mark + "Particle
 * Editor" + `● filename`. Right: native-style min / max-restore / close. The bar
 * (minus buttons) is the window's draggable caption (`app-region: drag`); the
 * buttons opt out (`no-drag`) and dispatch `window/*` host commands. Filename +
 * dirty mirror `document.title` (window-title.ts).
 *
 * In HEADLESS `--record` the interactive window controls are hidden (a close
 * button in a tutorial clip is noise) — the bar keeps mark + name + filename, so
 * a recorded clip is 1:1 with the live app minus the (non-clip) buttons.
 */
export function TitleBar({ bridge, currentFilePath, dirty }: TitleBarProps): ReactElement {
  const recording = useRecordHeadless();
  const [maximized, setMaximized] = useState(false);

  useEffect(() => bridge.on("window/state", (e) => setMaximized(e.payload.maximized)), [bridge]);

  const doc = currentFilePath ? basename(currentFilePath) : UNTITLED_DOC;
  const win = (kind: "window/minimize" | "window/maximize" | "window/close") =>
    void bridge.request({ kind, params: {} }).catch(() => {});

  return (
    <div
      data-testid="title-bar"
      className="flex h-[34px] shrink-0 select-none items-center gap-2.5 border-b border-border bg-panel pl-3 text-xs"
      style={DRAG}
    >
      {/* The real app mark — the ramped tile icon, identical to the taskbar/exe
          icon. Shown at 20px; the 40px source stays crisp at 1x–2x DPI. */}
      <img src={appMark} width={20} height={20} alt="" aria-hidden="true" className="shrink-0" />
      <span className="font-medium text-text">{APP_NAME}</span>
      <span className="h-4 w-px shrink-0 bg-border" aria-hidden="true" />
      {dirty && (
        <span className="text-accent" aria-hidden="true">
          ●
        </span>
      )}
      <span className="truncate text-text-2">{doc}</span>

      {/* Window controls — right-aligned, no-drag. Hidden in headless record. */}
      {!recording && (
        <div data-testid="window-controls" className="ml-auto flex h-full shrink-0 items-stretch" style={NO_DRAG}>
          <WinButton label="Minimize" onClick={() => win("window/minimize")}>
            <svg width="10" height="10" viewBox="0 0 10 10" aria-hidden="true">
              <line x1="0" y1="5" x2="10" y2="5" stroke="currentColor" strokeWidth="1" />
            </svg>
          </WinButton>
          <WinButton label={maximized ? "Restore" : "Maximize"} onClick={() => win("window/maximize")}>
            {maximized ? (
              <svg width="10" height="10" viewBox="0 0 10 10" fill="none" stroke="currentColor" strokeWidth="1" aria-hidden="true">
                <rect x="0.5" y="2.5" width="7" height="7" />
                <path d="M2.5 2.5 V0.5 H9.5 V7.5 H7.5" />
              </svg>
            ) : (
              <svg width="10" height="10" viewBox="0 0 10 10" fill="none" stroke="currentColor" strokeWidth="1" aria-hidden="true">
                <rect x="0.5" y="0.5" width="9" height="9" />
              </svg>
            )}
          </WinButton>
          <WinButton label="Close" close onClick={() => win("window/close")}>
            <svg width="10" height="10" viewBox="0 0 10 10" stroke="currentColor" strokeWidth="1" aria-hidden="true">
              <line x1="0" y1="0" x2="10" y2="10" />
              <line x1="10" y1="0" x2="0" y2="10" />
            </svg>
          </WinButton>
        </div>
      )}
    </div>
  );
}
